- hosts: all
  become: yes
  
  tasks:
    - name: update DNS server in /etc/sysconfig/network-scripts/ifcfg-eth0
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        state: present
        create: yes
        regexp: '^DNS1='
        line: 'DNS1={{DNSserver_ip}}'
    - name: restart network service
      service: name=network state=restarted
